import{i as l,S as c}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const u="https://pixabay.com/api",m="42048563-a2c01b7234988bf152885bd8d",i={form:document.getElementById("form"),resultContainer:document.getElementById("resultContainer"),gallery:document.getElementsByClassName(".gallery")};i.form.addEventListener("submit",f);function f(n){n.preventDefault();const r=n.currentTarget,t=r.elements.photoWrd.value;console.log(t),p(t).then(a=>{console.log(a);const e=a.hits;let o="";if(e.map(s=>{console.log(s),o+=d(s)}).join(""),i.gallery.innerHTML=o,h.refresh(),e.length===0){l.show({class:"error-svg",message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",messageSize:"16px",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",timeout:5e3});return}}).finally(()=>{r.reset()})}function p(n){const r=new URLSearchParams({key:m,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${u}/?${r}`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()}).catch(t=>console.log(t))}function d({webformatURL:n,largeImageURL:r,tags:t,likes:a,views:e,comments:o,downloads:s}){return`    
    <li class="photo_card">
    <a class="photo_link" href="${n}">
    <img class="photoLarge" src="${r}" alt="${t}"/>
    <p class="like">likes: "${a}"</p>
    <p class="views">views: "${e}"</p>
    <p class="comments">comments: "${o}"</p>
    <p class="downloads">downloads: "${s}"</p>
    </a>
    </li>`}const h=new c(".gallery a",{caption:!0,captionDelay:250,fadeSpeed:250,captionSelector:"img",captionsData:"alt",captionPosition:"bottom"});
//# sourceMappingURL=commonHelpers.js.map
